# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testprotocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testprotocol.proto',
  package='testi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12testprotocol.proto\x12\x05testi\",\n\x0b\x43hatmessage\x12\x10\n\x08senderID\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"A\n\x08Location\x12\x10\n\x08senderID\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\"3\n\x0cSendLocation\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\".\n\rSendLoginInfo\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"\"\n\x05Query\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\"U\n\nFromServer\x12#\n\x07\x63hatmsg\x18\x01 \x03(\x0b\x32\x12.testi.Chatmessage\x12\"\n\tlocations\x18\x02 \x03(\x0b\x32\x0f.testi.Location\"\x88\x01\n\x08ToServer\x12\x1b\n\x05query\x18\x01 \x01(\x0b\x32\x0c.testi.Query\x12\'\n\tlogininfo\x18\x02 \x01(\x0b\x32\x14.testi.SendLoginInfo\x12\x0f\n\x07\x63hatmsg\x18\x03 \x01(\t\x12%\n\x08location\x18\x04 \x01(\x0b\x32\x13.testi.SendLocationb\x06proto3')
)




_CHATMESSAGE = _descriptor.Descriptor(
  name='Chatmessage',
  full_name='testi.Chatmessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderID', full_name='testi.Chatmessage.senderID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='testi.Chatmessage.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=73,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='testi.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderID', full_name='testi.Location.senderID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='testi.Location.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='testi.Location.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=140,
)


_SENDLOCATION = _descriptor.Descriptor(
  name='SendLocation',
  full_name='testi.SendLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='testi.SendLocation.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='testi.SendLocation.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=193,
)


_SENDLOGININFO = _descriptor.Descriptor(
  name='SendLoginInfo',
  full_name='testi.SendLoginInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='testi.SendLoginInfo.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='testi.SendLoginInfo.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=241,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='testi.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='testi.Query.cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='testi.Query.args', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=277,
)


_FROMSERVER = _descriptor.Descriptor(
  name='FromServer',
  full_name='testi.FromServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chatmsg', full_name='testi.FromServer.chatmsg', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locations', full_name='testi.FromServer.locations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=364,
)


_TOSERVER = _descriptor.Descriptor(
  name='ToServer',
  full_name='testi.ToServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='testi.ToServer.query', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logininfo', full_name='testi.ToServer.logininfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chatmsg', full_name='testi.ToServer.chatmsg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='testi.ToServer.location', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=503,
)

_FROMSERVER.fields_by_name['chatmsg'].message_type = _CHATMESSAGE
_FROMSERVER.fields_by_name['locations'].message_type = _LOCATION
_TOSERVER.fields_by_name['query'].message_type = _QUERY
_TOSERVER.fields_by_name['logininfo'].message_type = _SENDLOGININFO
_TOSERVER.fields_by_name['location'].message_type = _SENDLOCATION
DESCRIPTOR.message_types_by_name['Chatmessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['SendLocation'] = _SENDLOCATION
DESCRIPTOR.message_types_by_name['SendLoginInfo'] = _SENDLOGININFO
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['FromServer'] = _FROMSERVER
DESCRIPTOR.message_types_by_name['ToServer'] = _TOSERVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chatmessage = _reflection.GeneratedProtocolMessageType('Chatmessage', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGE,
  '__module__' : 'testprotocol_pb2'
  # @@protoc_insertion_point(class_scope:testi.Chatmessage)
  })
_sym_db.RegisterMessage(Chatmessage)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
  'DESCRIPTOR' : _LOCATION,
  '__module__' : 'testprotocol_pb2'
  # @@protoc_insertion_point(class_scope:testi.Location)
  })
_sym_db.RegisterMessage(Location)

SendLocation = _reflection.GeneratedProtocolMessageType('SendLocation', (_message.Message,), {
  'DESCRIPTOR' : _SENDLOCATION,
  '__module__' : 'testprotocol_pb2'
  # @@protoc_insertion_point(class_scope:testi.SendLocation)
  })
_sym_db.RegisterMessage(SendLocation)

SendLoginInfo = _reflection.GeneratedProtocolMessageType('SendLoginInfo', (_message.Message,), {
  'DESCRIPTOR' : _SENDLOGININFO,
  '__module__' : 'testprotocol_pb2'
  # @@protoc_insertion_point(class_scope:testi.SendLoginInfo)
  })
_sym_db.RegisterMessage(SendLoginInfo)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'testprotocol_pb2'
  # @@protoc_insertion_point(class_scope:testi.Query)
  })
_sym_db.RegisterMessage(Query)

FromServer = _reflection.GeneratedProtocolMessageType('FromServer', (_message.Message,), {
  'DESCRIPTOR' : _FROMSERVER,
  '__module__' : 'testprotocol_pb2'
  # @@protoc_insertion_point(class_scope:testi.FromServer)
  })
_sym_db.RegisterMessage(FromServer)

ToServer = _reflection.GeneratedProtocolMessageType('ToServer', (_message.Message,), {
  'DESCRIPTOR' : _TOSERVER,
  '__module__' : 'testprotocol_pb2'
  # @@protoc_insertion_point(class_scope:testi.ToServer)
  })
_sym_db.RegisterMessage(ToServer)


# @@protoc_insertion_point(module_scope)
